server:
  port: 9090
  servlet:
    context-path: /api
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /
  pathsToMatch: /**
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_employee?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect:
          storage_engine: innodb
  data:
    jpa:
      repositories:
        enabled: true
environment:
  user-admin: admin@admin.com
  pass-admin: admin
  role-admin: admin-all-role