server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: employee-management
          uri: lb://employee-management
          predicates:
            - Path=/api/**
        - id: product-management
          uri: lb://product-management
          predicates:
            - Path=/api/**
        - id: purchase-management
          uri: lb://purchase-management
          predicates:
            - Path=/api/**
