server:
  port: ${PORT:${SERVER_PORT:0}}
  servlet:
    context-path: /product
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc
  pathsToMatch: /**
spring:
  application:
    zipkin: http://localhost:9411
  datasource:
    url: jdbc:postgresql://localhost:5432/db_product
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect:
          storage_engine: innodb
  data:
    jpa:
      repositories:
        enabled: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}