server:
  port: 9090
spring:
  cloud:
    config:
      server:
        git:
          default-label: multiple_instances
          uri: https://github.com/Jco24k/inventory_management
          search-paths: config-data
  application:
    name: config-server